### ISSUE TITLE
Can't install the packages. What are the exact versions?

### ISSUE THREAD

**Issue by EasonLin536** [ChristophReich1996/DeepFoveaPP_for_Video_Reconstruction_and_Super_Resolution#1]
Hi, I'm trying the full installation, but keep failing.
What are the "exact" versions for your packages (including CUDA).
Thanks.

**Comment by ChristophReich1996** [comment]
Hi @EasonLin536, could you share the exact error message? We used PyTorch 1.7.1 and CUDA 11.0 but other versions (PyTorch >1.0.0) should also pose no issues.

**Comment by EasonLin536** [comment]
Hi, @ChristophReich1996 , thank you for the reply.
After I built the `Deformable-Convolution` repo and install the `DCN==1.0` package, I copied the files in `build/lib.linux-x86_64-3.6/` to this repo.
When I execute `main.py`, the error message is
```bash
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    from model import RecurrentUNet
  File "/home/eason/Deep_Fovea_Architecture_for_Video_Super_Resolution/model.py", line 6, in <module>
    from modules.modulated_deform_conv import ModulatedDeformConvPack
  File "/home/eason/Deep_Fovea_Architecture_for_Video_Super_Resolution/modules/__init__.py", line 1, in <module>
    from .deform_conv import DeformConv, _DeformConv, DeformConvPack
  File "/home/eason/Deep_Fovea_Architecture_for_Video_Super_Resolution/modules/deform_conv.py", line 12, in <module>
    from functions.deform_conv_func import DeformConvFunction
  File "/home/eason/Deep_Fovea_Architecture_for_Video_Super_Resolution/functions/__init__.py", line 1, in <module>
    from .deform_conv_func import DeformConvFunction
  File "/home/eason/Deep_Fovea_Architecture_for_Video_Super_Resolution/functions/deform_conv_func.py", line 13, in <module>
    import DCN
ImportError: /home/eason/Deep_Fovea_Architecture_for_Video_Super_Resolution/DCN.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE
```
I'm using pytorch 1.0.0 and CUDA 9.0.
Thanks.

**Comment by ChristophReich1996** [comment]
Hi @EasonLin536, in case you cloned the [Deformable-Convolution-V2-PyTorch repo](https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch) into the DeepFovea++ folder/repo there should be no need for comping any files. Maybe consider updating to CUDA 10.0 or newer to avoid more issues.

Cheers
Christoph

**Comment by EasonLin536** [comment]
Hi, @ChristophReich1996, thanks for your help. I successfully installed DCN after updating to CUDA 11.0. However, in your **Full installation** section of `README`, shouldn't I cd into the `correlation/` folder to execute `python set_up.py install`? (the same with `resample/`). It appears to be some file missing if I execute in the repo directory. Not sure if I missed anything.

Thanks.

**Comment by ChristophReich1996** [comment]
Hi @EasonLin536, nice so installing all dependencies worked for you?
Yes, changing directory to the respective CUDA extension makes sense!
